// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: shared/proto/inventory/inventory.proto

package inventory

import (
	common "github.com/kgugunava/flash_sale_engine/shared/proto/common"
	order "github.com/kgugunava/flash_sale_engine/shared/proto/order"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReserveItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *order.Order           `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveItemsRequest) Reset() {
	*x = ReserveItemsRequest{}
	mi := &file_shared_proto_inventory_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveItemsRequest) ProtoMessage() {}

func (x *ReserveItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_inventory_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveItemsRequest.ProtoReflect.Descriptor instead.
func (*ReserveItemsRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_inventory_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *ReserveItemsRequest) GetOrder() *order.Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type CancelReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelReservationRequest) Reset() {
	*x = CancelReservationRequest{}
	mi := &file_shared_proto_inventory_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelReservationRequest) ProtoMessage() {}

func (x *CancelReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_inventory_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelReservationRequest.ProtoReflect.Descriptor instead.
func (*CancelReservationRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_inventory_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *CancelReservationRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

type ReserveItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	Status        *common.ResponseStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Error         *common.ResponseError  `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveItemsResponse) Reset() {
	*x = ReserveItemsResponse{}
	mi := &file_shared_proto_inventory_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveItemsResponse) ProtoMessage() {}

func (x *ReserveItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_inventory_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveItemsResponse.ProtoReflect.Descriptor instead.
func (*ReserveItemsResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_inventory_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *ReserveItemsResponse) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ReserveItemsResponse) GetStatus() *common.ResponseStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ReserveItemsResponse) GetError() *common.ResponseError {
	if x != nil {
		return x.Error
	}
	return nil
}

type CancelReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	Status        *common.ResponseStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Error         *common.ResponseError  `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelReservationResponse) Reset() {
	*x = CancelReservationResponse{}
	mi := &file_shared_proto_inventory_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelReservationResponse) ProtoMessage() {}

func (x *CancelReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_inventory_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelReservationResponse.ProtoReflect.Descriptor instead.
func (*CancelReservationResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_inventory_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *CancelReservationResponse) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *CancelReservationResponse) GetStatus() *common.ResponseStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *CancelReservationResponse) GetError() *common.ResponseError {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_shared_proto_inventory_inventory_proto protoreflect.FileDescriptor

const file_shared_proto_inventory_inventory_proto_rawDesc = "" +
	"\n" +
	"&shared/proto/inventory/inventory.proto\x12\tinventory\x1a shared/proto/common/common.proto\x1a\x1eshared/proto/order/order.proto\"9\n" +
	"\x13ReserveItemsRequest\x12\"\n" +
	"\x05order\x18\x01 \x01(\v2\f.order.OrderR\x05order\"A\n" +
	"\x18CancelReservationRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\"\x9a\x01\n" +
	"\x14ReserveItemsResponse\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12.\n" +
	"\x06status\x18\x02 \x01(\v2\x16.common.ResponseStatusR\x06status\x12+\n" +
	"\x05error\x18\x03 \x01(\v2\x15.common.ResponseErrorR\x05error\"\x9f\x01\n" +
	"\x19CancelReservationResponse\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12.\n" +
	"\x06status\x18\x02 \x01(\v2\x16.common.ResponseStatusR\x06status\x12+\n" +
	"\x05error\x18\x03 \x01(\v2\x15.common.ResponseErrorR\x05error2\xc3\x01\n" +
	"\x10InventoryService\x12O\n" +
	"\fReserveItems\x12\x1e.inventory.ReserveItemsRequest\x1a\x1f.inventory.ReserveItemsResponse\x12^\n" +
	"\x11CancelReservation\x12#.inventory.CancelReservationRequest\x1a$.inventory.CancelReservationResponseB?Z=github.com/kgugunava/flash_sale_engine/shared/proto/inventoryb\x06proto3"

var (
	file_shared_proto_inventory_inventory_proto_rawDescOnce sync.Once
	file_shared_proto_inventory_inventory_proto_rawDescData []byte
)

func file_shared_proto_inventory_inventory_proto_rawDescGZIP() []byte {
	file_shared_proto_inventory_inventory_proto_rawDescOnce.Do(func() {
		file_shared_proto_inventory_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_inventory_inventory_proto_rawDesc), len(file_shared_proto_inventory_inventory_proto_rawDesc)))
	})
	return file_shared_proto_inventory_inventory_proto_rawDescData
}

var file_shared_proto_inventory_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_shared_proto_inventory_inventory_proto_goTypes = []any{
	(*ReserveItemsRequest)(nil),       // 0: inventory.ReserveItemsRequest
	(*CancelReservationRequest)(nil),  // 1: inventory.CancelReservationRequest
	(*ReserveItemsResponse)(nil),      // 2: inventory.ReserveItemsResponse
	(*CancelReservationResponse)(nil), // 3: inventory.CancelReservationResponse
	(*order.Order)(nil),               // 4: order.Order
	(*common.ResponseStatus)(nil),     // 5: common.ResponseStatus
	(*common.ResponseError)(nil),      // 6: common.ResponseError
}
var file_shared_proto_inventory_inventory_proto_depIdxs = []int32{
	4, // 0: inventory.ReserveItemsRequest.order:type_name -> order.Order
	5, // 1: inventory.ReserveItemsResponse.status:type_name -> common.ResponseStatus
	6, // 2: inventory.ReserveItemsResponse.error:type_name -> common.ResponseError
	5, // 3: inventory.CancelReservationResponse.status:type_name -> common.ResponseStatus
	6, // 4: inventory.CancelReservationResponse.error:type_name -> common.ResponseError
	0, // 5: inventory.InventoryService.ReserveItems:input_type -> inventory.ReserveItemsRequest
	1, // 6: inventory.InventoryService.CancelReservation:input_type -> inventory.CancelReservationRequest
	2, // 7: inventory.InventoryService.ReserveItems:output_type -> inventory.ReserveItemsResponse
	3, // 8: inventory.InventoryService.CancelReservation:output_type -> inventory.CancelReservationResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_shared_proto_inventory_inventory_proto_init() }
func file_shared_proto_inventory_inventory_proto_init() {
	if File_shared_proto_inventory_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_inventory_inventory_proto_rawDesc), len(file_shared_proto_inventory_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_proto_inventory_inventory_proto_goTypes,
		DependencyIndexes: file_shared_proto_inventory_inventory_proto_depIdxs,
		MessageInfos:      file_shared_proto_inventory_inventory_proto_msgTypes,
	}.Build()
	File_shared_proto_inventory_inventory_proto = out.File
	file_shared_proto_inventory_inventory_proto_goTypes = nil
	file_shared_proto_inventory_inventory_proto_depIdxs = nil
}
