// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: shared/proto/inventory/inventory.proto

package inventory

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReturnItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReturnItemRequest) Reset() {
	*x = ReturnItemRequest{}
	mi := &file_shared_proto_inventory_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReturnItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnItemRequest) ProtoMessage() {}

func (x *ReturnItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_inventory_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnItemRequest.ProtoReflect.Descriptor instead.
func (*ReturnItemRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_inventory_inventory_proto_rawDescGZIP(), []int{0}
}

type ReserveItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveItemRequest) Reset() {
	*x = ReserveItemRequest{}
	mi := &file_shared_proto_inventory_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveItemRequest) ProtoMessage() {}

func (x *ReserveItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_inventory_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveItemRequest.ProtoReflect.Descriptor instead.
func (*ReserveItemRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_inventory_inventory_proto_rawDescGZIP(), []int{1}
}

type ReturnItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReturnItemResponse) Reset() {
	*x = ReturnItemResponse{}
	mi := &file_shared_proto_inventory_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReturnItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnItemResponse) ProtoMessage() {}

func (x *ReturnItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_inventory_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnItemResponse.ProtoReflect.Descriptor instead.
func (*ReturnItemResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_inventory_inventory_proto_rawDescGZIP(), []int{2}
}

type ReserveItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveItemResponse) Reset() {
	*x = ReserveItemResponse{}
	mi := &file_shared_proto_inventory_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveItemResponse) ProtoMessage() {}

func (x *ReserveItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_inventory_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveItemResponse.ProtoReflect.Descriptor instead.
func (*ReserveItemResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_inventory_inventory_proto_rawDescGZIP(), []int{3}
}

var File_shared_proto_inventory_inventory_proto protoreflect.FileDescriptor

const file_shared_proto_inventory_inventory_proto_rawDesc = "" +
	"\n" +
	"&shared/proto/inventory/inventory.proto\x12\tinventory\"\x13\n" +
	"\x11ReturnItemRequest\"\x14\n" +
	"\x12ReserveItemRequest\"\x14\n" +
	"\x12ReturnItemResponse\"\x15\n" +
	"\x13ReserveItemResponse2\xb8\x01\n" +
	"\x10InventoryService\x12L\n" +
	"\vReserveItem\x12\x1d.inventory.ReserveItemRequest\x1a\x1e.inventory.ReserveItemResponse\x12V\n" +
	"\x17ReturnItemBeforePayment\x12\x1c.inventory.ReturnItemRequest\x1a\x1d.inventory.ReturnItemResponseB?Z=github.com/kgugunava/flash_sale_engine/shared/proto/inventoryb\x06proto3"

var (
	file_shared_proto_inventory_inventory_proto_rawDescOnce sync.Once
	file_shared_proto_inventory_inventory_proto_rawDescData []byte
)

func file_shared_proto_inventory_inventory_proto_rawDescGZIP() []byte {
	file_shared_proto_inventory_inventory_proto_rawDescOnce.Do(func() {
		file_shared_proto_inventory_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_inventory_inventory_proto_rawDesc), len(file_shared_proto_inventory_inventory_proto_rawDesc)))
	})
	return file_shared_proto_inventory_inventory_proto_rawDescData
}

var file_shared_proto_inventory_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_shared_proto_inventory_inventory_proto_goTypes = []any{
	(*ReturnItemRequest)(nil),   // 0: inventory.ReturnItemRequest
	(*ReserveItemRequest)(nil),  // 1: inventory.ReserveItemRequest
	(*ReturnItemResponse)(nil),  // 2: inventory.ReturnItemResponse
	(*ReserveItemResponse)(nil), // 3: inventory.ReserveItemResponse
}
var file_shared_proto_inventory_inventory_proto_depIdxs = []int32{
	1, // 0: inventory.InventoryService.ReserveItem:input_type -> inventory.ReserveItemRequest
	0, // 1: inventory.InventoryService.ReturnItemBeforePayment:input_type -> inventory.ReturnItemRequest
	3, // 2: inventory.InventoryService.ReserveItem:output_type -> inventory.ReserveItemResponse
	2, // 3: inventory.InventoryService.ReturnItemBeforePayment:output_type -> inventory.ReturnItemResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shared_proto_inventory_inventory_proto_init() }
func file_shared_proto_inventory_inventory_proto_init() {
	if File_shared_proto_inventory_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_inventory_inventory_proto_rawDesc), len(file_shared_proto_inventory_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_proto_inventory_inventory_proto_goTypes,
		DependencyIndexes: file_shared_proto_inventory_inventory_proto_depIdxs,
		MessageInfos:      file_shared_proto_inventory_inventory_proto_msgTypes,
	}.Build()
	File_shared_proto_inventory_inventory_proto = out.File
	file_shared_proto_inventory_inventory_proto_goTypes = nil
	file_shared_proto_inventory_inventory_proto_depIdxs = nil
}
