// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: shared/proto/order/order.proto

package order

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ItemName      string                 `protobuf:"bytes,2,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_shared_proto_order_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_order_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_order_order_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateOrderRequest) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *CreateOrderRequest) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_shared_proto_order_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_order_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_order_order_proto_rawDescGZIP(), []int{1}
}

func (x *CancelOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type GetOrdersListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersListRequest) Reset() {
	*x = GetOrdersListRequest{}
	mi := &file_shared_proto_order_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersListRequest) ProtoMessage() {}

func (x *GetOrdersListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_order_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersListRequest.ProtoReflect.Descriptor instead.
func (*GetOrdersListRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_order_order_proto_rawDescGZIP(), []int{2}
}

type GetUserOrdersListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserOrdersListRequest) Reset() {
	*x = GetUserOrdersListRequest{}
	mi := &file_shared_proto_order_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserOrdersListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserOrdersListRequest) ProtoMessage() {}

func (x *GetUserOrdersListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_order_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserOrdersListRequest.ProtoReflect.Descriptor instead.
func (*GetUserOrdersListRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_order_order_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserOrdersListRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_shared_proto_order_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_order_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_order_order_proto_rawDescGZIP(), []int{4}
}

type CancelOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderResponse) Reset() {
	*x = CancelOrderResponse{}
	mi := &file_shared_proto_order_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderResponse) ProtoMessage() {}

func (x *CancelOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_order_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderResponse.ProtoReflect.Descriptor instead.
func (*CancelOrderResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_order_order_proto_rawDescGZIP(), []int{5}
}

type GetOrdersListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersListResponse) Reset() {
	*x = GetOrdersListResponse{}
	mi := &file_shared_proto_order_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersListResponse) ProtoMessage() {}

func (x *GetOrdersListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_order_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersListResponse.ProtoReflect.Descriptor instead.
func (*GetOrdersListResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_order_order_proto_rawDescGZIP(), []int{6}
}

type GetUserOrdersListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserOrdersListResponse) Reset() {
	*x = GetUserOrdersListResponse{}
	mi := &file_shared_proto_order_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserOrdersListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserOrdersListResponse) ProtoMessage() {}

func (x *GetUserOrdersListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_order_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserOrdersListResponse.ProtoReflect.Descriptor instead.
func (*GetUserOrdersListResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_order_order_proto_rawDescGZIP(), []int{7}
}

var File_shared_proto_order_order_proto protoreflect.FileDescriptor

const file_shared_proto_order_order_proto_rawDesc = "" +
	"\n" +
	"\x1eshared/proto/order/order.proto\x12\x05order\x1a\x1fgoogle/protobuf/timestamp.proto\"z\n" +
	"\x12CreateOrderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\titem_name\x18\x02 \x01(\tR\bitemName\x12.\n" +
	"\x04time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\"/\n" +
	"\x12CancelOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"\x16\n" +
	"\x14GetOrdersListRequest\"3\n" +
	"\x18GetUserOrdersListRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x15\n" +
	"\x13CreateOrderResponse\"\x15\n" +
	"\x13CancelOrderResponse\"\x17\n" +
	"\x15GetOrdersListResponse\"\x1b\n" +
	"\x19GetUserOrdersListResponse2\xbe\x02\n" +
	"\fOrderService\x12D\n" +
	"\vCreateOrder\x12\x19.order.CreateOrderRequest\x1a\x1a.order.CreateOrderResponse\x12D\n" +
	"\vCancelOrder\x12\x19.order.CancelOrderRequest\x1a\x1a.order.CancelOrderResponse\x12J\n" +
	"\rGetOrdersList\x12\x1b.order.GetOrdersListRequest\x1a\x1c.order.GetOrdersListResponse\x12V\n" +
	"\x11GetUserOrdersList\x12\x1f.order.GetUserOrdersListRequest\x1a .order.GetUserOrdersListResponseB;Z9github.com/kgugunava/flash_sale_engine/shared/proto/orderb\x06proto3"

var (
	file_shared_proto_order_order_proto_rawDescOnce sync.Once
	file_shared_proto_order_order_proto_rawDescData []byte
)

func file_shared_proto_order_order_proto_rawDescGZIP() []byte {
	file_shared_proto_order_order_proto_rawDescOnce.Do(func() {
		file_shared_proto_order_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_order_order_proto_rawDesc), len(file_shared_proto_order_order_proto_rawDesc)))
	})
	return file_shared_proto_order_order_proto_rawDescData
}

var file_shared_proto_order_order_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_shared_proto_order_order_proto_goTypes = []any{
	(*CreateOrderRequest)(nil),        // 0: order.CreateOrderRequest
	(*CancelOrderRequest)(nil),        // 1: order.CancelOrderRequest
	(*GetOrdersListRequest)(nil),      // 2: order.GetOrdersListRequest
	(*GetUserOrdersListRequest)(nil),  // 3: order.GetUserOrdersListRequest
	(*CreateOrderResponse)(nil),       // 4: order.CreateOrderResponse
	(*CancelOrderResponse)(nil),       // 5: order.CancelOrderResponse
	(*GetOrdersListResponse)(nil),     // 6: order.GetOrdersListResponse
	(*GetUserOrdersListResponse)(nil), // 7: order.GetUserOrdersListResponse
	(*timestamppb.Timestamp)(nil),     // 8: google.protobuf.Timestamp
}
var file_shared_proto_order_order_proto_depIdxs = []int32{
	8, // 0: order.CreateOrderRequest.time:type_name -> google.protobuf.Timestamp
	0, // 1: order.OrderService.CreateOrder:input_type -> order.CreateOrderRequest
	1, // 2: order.OrderService.CancelOrder:input_type -> order.CancelOrderRequest
	2, // 3: order.OrderService.GetOrdersList:input_type -> order.GetOrdersListRequest
	3, // 4: order.OrderService.GetUserOrdersList:input_type -> order.GetUserOrdersListRequest
	4, // 5: order.OrderService.CreateOrder:output_type -> order.CreateOrderResponse
	5, // 6: order.OrderService.CancelOrder:output_type -> order.CancelOrderResponse
	6, // 7: order.OrderService.GetOrdersList:output_type -> order.GetOrdersListResponse
	7, // 8: order.OrderService.GetUserOrdersList:output_type -> order.GetUserOrdersListResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_shared_proto_order_order_proto_init() }
func file_shared_proto_order_order_proto_init() {
	if File_shared_proto_order_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_order_order_proto_rawDesc), len(file_shared_proto_order_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_proto_order_order_proto_goTypes,
		DependencyIndexes: file_shared_proto_order_order_proto_depIdxs,
		MessageInfos:      file_shared_proto_order_order_proto_msgTypes,
	}.Build()
	File_shared_proto_order_order_proto = out.File
	file_shared_proto_order_order_proto_goTypes = nil
	file_shared_proto_order_order_proto_depIdxs = nil
}
