// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: shared/proto/payment/payment.proto

package payment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MakePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakePaymentRequest) Reset() {
	*x = MakePaymentRequest{}
	mi := &file_shared_proto_payment_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakePaymentRequest) ProtoMessage() {}

func (x *MakePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_payment_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakePaymentRequest.ProtoReflect.Descriptor instead.
func (*MakePaymentRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_payment_payment_proto_rawDescGZIP(), []int{0}
}

type MakePaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakePaymentResponse) Reset() {
	*x = MakePaymentResponse{}
	mi := &file_shared_proto_payment_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakePaymentResponse) ProtoMessage() {}

func (x *MakePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_payment_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakePaymentResponse.ProtoReflect.Descriptor instead.
func (*MakePaymentResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_payment_payment_proto_rawDescGZIP(), []int{1}
}

var File_shared_proto_payment_payment_proto protoreflect.FileDescriptor

const file_shared_proto_payment_payment_proto_rawDesc = "" +
	"\n" +
	"\"shared/proto/payment/payment.proto\x12\apayment\"\x14\n" +
	"\x12MakePaymentRequest\"\x15\n" +
	"\x13MakePaymentResponse2Z\n" +
	"\x0ePaymentService\x12H\n" +
	"\vMakePayment\x12\x1b.payment.MakePaymentRequest\x1a\x1c.payment.MakePaymentResponseB=Z;github.com/kgugunava/flash_sale_engine/shared/proto/paymentb\x06proto3"

var (
	file_shared_proto_payment_payment_proto_rawDescOnce sync.Once
	file_shared_proto_payment_payment_proto_rawDescData []byte
)

func file_shared_proto_payment_payment_proto_rawDescGZIP() []byte {
	file_shared_proto_payment_payment_proto_rawDescOnce.Do(func() {
		file_shared_proto_payment_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_payment_payment_proto_rawDesc), len(file_shared_proto_payment_payment_proto_rawDesc)))
	})
	return file_shared_proto_payment_payment_proto_rawDescData
}

var file_shared_proto_payment_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_shared_proto_payment_payment_proto_goTypes = []any{
	(*MakePaymentRequest)(nil),  // 0: payment.MakePaymentRequest
	(*MakePaymentResponse)(nil), // 1: payment.MakePaymentResponse
}
var file_shared_proto_payment_payment_proto_depIdxs = []int32{
	0, // 0: payment.PaymentService.MakePayment:input_type -> payment.MakePaymentRequest
	1, // 1: payment.PaymentService.MakePayment:output_type -> payment.MakePaymentResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shared_proto_payment_payment_proto_init() }
func file_shared_proto_payment_payment_proto_init() {
	if File_shared_proto_payment_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_payment_payment_proto_rawDesc), len(file_shared_proto_payment_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_proto_payment_payment_proto_goTypes,
		DependencyIndexes: file_shared_proto_payment_payment_proto_depIdxs,
		MessageInfos:      file_shared_proto_payment_payment_proto_msgTypes,
	}.Build()
	File_shared_proto_payment_payment_proto = out.File
	file_shared_proto_payment_payment_proto_goTypes = nil
	file_shared_proto_payment_payment_proto_depIdxs = nil
}
